Repository prgrms-web-devcourse-final-project/WEB1_2_PublicPlus_FE, pull requests merged in 2024-12, with the labels that each got.

#60 🐛 Fix: develop 병합으로 인한 시설 쪽 에러 처리 및 UI 수정
  src/app/(default-layout)/facility/[id]/page.tsx
  src/app/layout.tsx
  src/features/facility/ui/CreateMeetingButton.tsx
  src/features/facility/ui/FacilityReviews.tsx
  src/shared/config/metadata/constants.ts
  src/shared/config/metadata/default-metadata.ts
  src/shared/config/metadata/generate-metadata.ts
Labels: bug

#77 [Qtvy 117] Lighthouse CI를 사용한 PR 머지 후 성능 및 품질 자동화 테스트 추가
  .github/workflows/lighthouse.yml
Labels: performance, feature

#88 Qtvy 122 meeting UI
  .github/workflows/deployment.yml
  package.json
  pnpm-lock.yaml
  src/app/(default-layout)/layout.tsx
  src/app/(default-layout)/meeting/[id]/page.tsx
  src/app/(default-layout)/meeting/create/page.tsx
  src/app/(default-layout)/meeting/page.tsx
  src/components/common/Cards/MeetingCard.tsx
  src/components/common/Header/Header.tsx
  src/entities/meetingBoard/api/meetingBoardService.ts
  src/features/facility/model/queries.ts
  src/features/facility/ui/CreateMeetingButton.tsx
  src/features/facility/ui/FacilityHeader.tsx
  src/features/facility/ui/FacilityReviews.tsx
  src/features/meeting/index.tsx
  src/features/meeting/model/queries.ts
  src/features/meeting/ui/CreateMeetingForm.tsx
  src/features/meeting/ui/MeetingComments.tsx
  src/features/meeting/ui/MeetingHeader.tsx
  src/features/meeting/ui/MeetingInfo.tsx
  src/features/meeting/ui/MeetingTabs.tsx
  src/mocks/data/meetingBoardData.ts
  src/mocks/db/meetingDb.ts
  src/mocks/db/reviewDb.ts
  src/mocks/handlers/index.ts
  src/mocks/handlers/meetingHandlers.ts
  src/mocks/handlers/reviewHandlers.ts
  src/shared/api/client.ts
  src/shared/config/constants.ts
  src/shared/ui/Map/PageHeader.tsx
  src/widgets/meeting/meeting-detail/index.tsx
  src/widgets/meeting/meeting-list/index.tsx
Labels: feature

#91 ✏️ Fix: CICD 워크플로우 수정
  .github/workflows/deployment.yml
Labels: bug

#94 ✏️ Fix: 배포 워크플로우 수정
  .github/workflows/deployment.yml
  next.config.ts
Labels: bug

#97 🐛 Fix: Lambda 배포 중 RequestEntityTooLargeException 에러 처리
  .github/workflows/deployment.yml
Labels: bug

#100 🐛 Fix: S3 크로스 리전 접근 디버그 로그 추가
  .github/workflows/deployment.yml
Labels: bug

#105 🐛 Fix: 타입과 일반 import를 통합
  .eslintrc.json
  src/components/common/Header/CustomHeader.tsx
  src/middleware.ts
Labels: bug

#113 Feat: 비밀번호 재설정, 회원탈퇴
  src/app/(default-layout)/profile/edit/page.tsx
  src/app/(default-layout)/profile/edit/password/layout.tsx
  src/app/(default-layout)/profile/edit/password/page.tsx
  src/app/style-guide/page.tsx
  src/components/common/Cards/EditCard.tsx
  src/components/common/Modal.tsx
  src/entities/User/api/userService.ts
  src/entities/User/model/store/authStore.ts
  src/entities/User/model/types/AuthState.ts
  src/features/mypage/hooks/useChangePassword.ts
  src/features/mypage/ui/UserProfile.tsx
  src/mocks/handlers/authHandlers.ts
Labels: feature
