Repository prgrms-web-devcourse-final-project/WEB1_2_PublicPlus_FE, pull requests merged in 2024-11, with the labels that each got.

#38 🐛 Fix: 빌드 전 타입 에러 처리
  src/app/style-guide/page.tsx
  src/components/common/Cards/MeetingCard.tsx
  src/components/common/Cards/constants.ts
  src/features/facility/filter/model/store.ts
Labels: bug

#39 ✨ RootLayout 에 ErrorBoundary 및 Suspense 적용
  src/app/layout.tsx
  src/components/ErrorBoundary/ErrorBoundary.tsx
  src/components/ErrorBoundary/ErrorFallback.tsx
  src/components/FacilityDetailClient.tsx
  src/components/Suspense/Loading.tsx
Labels: ui/ux

#43 ✨ Feat: login UI - #Qtvy-93
  public/icons/google.png
  public/icons/kakaotalk.png
  public/icons/left-arrow.png
  public/icons/more_horiz.png
  public/icons/naver.png
  src/app/(default-layout)/layout.tsx
  src/app/(empty-layout)/(auth)/login/page.tsx
  src/app/(empty-layout)/(auth)/signup/complete/page.tsx
  src/app/(empty-layout)/(auth)/signup/email/page.tsx
  src/app/(empty-layout)/(auth)/signup/layout.tsx
  src/app/(empty-layout)/(auth)/signup/nickname/page.tsx
  src/app/(empty-layout)/(auth)/signup/password/page.tsx
  src/app/(empty-layout)/layout.tsx
  src/app/(empty-layout)/login/page.tsx
  src/app/style-guide/chat/page.tsx
  src/components/common/Header/CustomHeader.module.css
  src/components/common/Header/CustomHeader.tsx
  src/components/common/Header/Header.module.css
  src/components/common/Navigation/Navigation.module.css
  src/features/auth/hooks/useNicknameValidation.ts
  src/features/auth/hooks/usePasswordValidation.ts
  src/features/auth/ui/EmailInput.tsx
  src/features/auth/ui/LoginContainer.tsx
  src/features/auth/ui/LoginForm.tsx
  src/features/auth/ui/NickNameForm.tsx
  src/features/auth/ui/PasswordConfirmField.tsx
  src/features/auth/ui/PasswordField.tsx
  src/features/auth/ui/PasswordForm.tsx
  src/features/auth/ui/SignupForm.tsx
  src/features/auth/ui/VerificationInput.tsx
  src/mocks/data/authData.ts
  src/mocks/data/userData.ts
  src/mocks/handlers/authHandlers.ts
  src/mocks/handlers/index.ts
  src/mocks/types/UserTypes.ts
  src/styles/globals.css
  stores/authStore.ts
Labels: ui/ux, feature

#45 Qtvy 102 review UI
  .github/workflows/issue-close-jira.yml
  .storybook/preview.ts
  openapitools.json
  package.json
  pnpm-lock.yaml
  public/icons/Heart.png
  public/icons/back-arrow.png
  public/icons/heart-filled.png
  src/api/generated/.gitignore
  src/api/generated/.npmignore
  src/api/generated/.openapi-generator-ignore
  src/api/generated/.openapi-generator/FILES
  src/api/generated/.openapi-generator/VERSION
  src/api/generated/api.ts
  src/api/generated/base.ts
  src/api/generated/common.ts
  src/api/generated/configuration.ts
  src/api/generated/git_push.sh
  src/api/generated/index.ts
  src/app/(default-layout)/facility/[id]/page.tsx
  src/app/(default-layout)/layout.tsx
  src/components/FacilityDetailClient.tsx
  src/components/common/Cards/LinkCard.tsx
  src/components/common/Header/Header.module.css
  src/components/common/Header/Header.tsx
  src/entities/facility/api/facilityService.ts
  src/entities/facility/model/store.ts
  src/entities/facility/model/types/index.ts
  src/entities/review/model/types.ts
  src/features/facility/filter/model/store.ts
  src/features/facility/filter/ui/area-filter.tsx
  src/features/facility/index.ts
  src/features/facility/model/queries.ts
  src/features/facility/model/store.ts
  src/features/facility/ui/CreateMeetingButton.tsx
  src/features/facility/ui/FacilityHeader.tsx
  src/features/facility/ui/FacilityInfo.tsx
  src/features/facility/ui/FacilityReviews.tsx
  src/features/facility/ui/FacilityRules.tsx
  src/features/facility/ui/FacilityTabs.tsx
  src/mocks/data/facilityData.ts
  src/mocks/handlers/facilityHandlers.ts
  src/mocks/handlers/pagination.ts
  src/shared/api/axios.ts
  src/shared/api/client.ts
  src/shared/api/endpoints.ts
  src/shared/config/constants.ts
  src/shared/ui/Map/KakaoMap.tsx
  src/styles/globals.css
  src/widgets/facility/facility-detail/index.tsx
  src/widgets/facility/facility-list/index.tsx
  swagger.json
  tailwind.config.ts
Labels: feature

#47 Qtvy 104 mypage UI
  next.config.ts
  package.json
  pnpm-lock.yaml
  public/icons/nav/chat-active.png
  public/icons/nav/facilities-active.png
  public/icons/nav/home-active.png
  public/icons/nav/meetings-active.png
  public/icons/nav/mypage-active.png
  src/app/(default-layout)/layout.tsx
  src/app/(default-layout)/profile/edit/description/page.tsx
  src/app/(default-layout)/profile/edit/nickname/page.tsx
  src/app/(default-layout)/profile/edit/page.tsx
  src/app/(default-layout)/profile/edit/profileimage/page.tsx
  src/app/(default-layout)/profile/page.tsx
  src/app/(empty-layout)/notifications/page.tsx
  src/components/common/Cards/Card.tsx
  src/components/common/Cards/EditCard.tsx
  src/components/common/Cards/UserInfoCard.tsx
  src/components/common/ErrorMsg.tsx
  src/components/common/Header/Header.tsx
  src/components/common/Navigation/NavItem.module.css
  src/components/common/Navigation/constants.ts
  src/components/common/Navigation/types.ts
  src/components/common/NotificationItem.tsx
  src/components/common/Tag.tsx
  src/features/mypage/types.ts
  src/features/mypage/ui/EditLayout.tsx
  src/features/mypage/ui/MypageTap.tsx
  src/features/mypage/ui/UserInfo.tsx
  src/features/mypage/ui/UserProfile.tsx
  src/features/notifications/ui/NotificationList.tsx
  src/features/review/ui/UserReviews.tsx
  src/mocks/data/userData.ts
  src/mocks/handlers/authHandlers.ts
  src/mocks/types/UserTypes.ts
  stores/authStore.ts
  tailwind.config.ts
Labels: feature

#52 Feat: SwaggerHub 연동 및 API 클라이언트 동기화 워크플로우
  .github/workflows/api-client-generation.yml
  package.json
  src/api/generated/.swagger-codegen-ignore
  src/api/generated/.swagger-codegen/VERSION
  src/api/generated/README.md
  src/api/generated/api.ts
  src/api/generated/swagger.json
  swagger.json
Labels: feature

#56 Qtvy 112 map
  .github/workflows/api-client-generation.yml
  package.json
  pnpm-lock.yaml
  src/api/generated/api.ts
  src/components/common/Button/Button.tsx
  src/components/common/Cards/Card.tsx
  src/components/common/Input.tsx
  src/entities/review/api/reviewService.ts
  src/entities/review/model/types/types.ts
  src/features/auth/hooks/useUser.ts
  src/features/auth/index.ts
  src/features/auth/model/store.ts
  src/features/auth/types/index.ts
  src/features/facility/ui/FacilityReviews.tsx
  src/features/review/model/queries.ts
  src/features/review/model/store.ts
  src/features/review/ui/ReviewForm.tsx
  src/mocks/data/reviewData.ts
  src/mocks/handlers/index.ts
  src/mocks/handlers/reviewHandlers.ts
  src/shared/api/axiosInstance.ts
  src/shared/api/client.ts
  src/shared/lib/utils.ts
  src/styles/globals.css
  src/widgets/rating/Rating.tsx
  src/widgets/tag-input/TagInput.tsx
  tailwind.config.ts
Labels: feature
